"""add password to table users

Revision ID: 3678d0da3c4e
Revises: 9ff8ad91f7f3
Create Date: 2025-11-02 22:02:33.626257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext


# revision identifiers, used by Alembic.
revision: str = '3678d0da3c4e'
down_revision: Union[str, Sequence[str], None] = '9ff8ad91f7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    
    # Hash the default password
    hashed_default_password = pwd_context.hash("User#123")
    
    op.add_column("users", sa.Column("password", sa.Text(), nullable=False, server_default=hashed_default_password))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
