"""alter book table add description field

Revision ID: 4172bdb04b21
Revises: b67c20769721
Create Date: 2025-10-25 13:25:24.488320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4172bdb04b21'
down_revision: Union[str, Sequence[str], None] = 'b67c20769721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.Text(), nullable=False))
    op.drop_constraint(op.f('books_name_key'), 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['description'])
    op.drop_column('books', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint(op.f('books_name_key'), 'books', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
