"""alter table book add url and image url field

Revision ID: b67c20769721
Revises: 051a3411d206
Create Date: 2025-10-25 12:46:21.679191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c20769721'
down_revision: Union[str, Sequence[str], None] = '051a3411d206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image_url')
    op.drop_column('books', 'url')
    # ### end Alembic commands ###
