"""add authors books

Revision ID: f0c9264795eb
Revises: a51d09bbbc9d
Create Date: 2025-11-24 00:22:45.357707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c9264795eb'
down_revision: Union[str, Sequence[str], None] = 'a51d09bbbc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("authors",
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_rating', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    )
    op.create_table("authors_books",
    sa.Column("author_id", sa.Integer(), sa.ForeignKey("authors.id", ondelete="CASCADE"), primary_key=True),
    sa.Column("book_id", sa.Integer(), sa.ForeignKey("books.id", ondelete="CASCADE"), primary_key=True),
    sa.PrimaryKeyConstraint('author_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authors_books")
    op.drop_table("authors")
    # ### end Alembic commands ###
